name: Pull Request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Pytest
        uses: microsoft/action-python@0.7.0
        with:
          testing: pytest
          run: pytest test01.py
