name: test01
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  test01:
    runs-on: windows-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
     #Setup Python   
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
    #Install Chrome packages and run pytest
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
      - run: chrome --version
      - name: Install the necessary packages
        run: pip install --upgrade pip selenium pytest allure-pytest
      - name: Run the PytTest script
        run: pytest test01.py
